name: "Check opened PR action"
description: "Check that the commit that triggered the workflow run exists as opened PR."
inputs:
  github-token:
    description: "A token to authenticate on behalf of the GitHub App installed on your repository. This is functionally equivalent to the GITHUB_TOKEN secret."
    required: true
    default: ${{ github.token }}
outputs:
  exists:
    description: "true if the commit that triggered the workflow run exists as opened PR, false otherwise."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "blue"
